// generated by stringer -type=JobMessageType; DO NOT EDIT

package controllers

import "fmt"

const _JobMessageType_name = "NormalError"

var _JobMessageType_index = [...]uint8{0, 6, 11}

func (i JobMessageType) String() string {
	i -= 1
	if i < 0 || i >= JobMessageType(len(_JobMessageType_index)-1) {
		return fmt.Sprintf("JobMessageType(%d)", i+1)
	}
	return _JobMessageType_name[_JobMessageType_index[i]:_JobMessageType_index[i+1]]
}
