// generated by stringer -type=Status; DO NOT EDIT

package controllers

import "fmt"

const _Status_name = "WaitingToRunRunningFinishedCannotRun"

var _Status_index = [...]uint8{0, 12, 19, 27, 36}

func (i Status) String() string {
	i -= 1
	if i < 0 || i >= Status(len(_Status_index)-1) {
		return fmt.Sprintf("Status(%d)", i+1)
	}
	return _Status_name[_Status_index[i]:_Status_index[i+1]]
}
