// generated by stringer -type=JobStatus models/models.go; DO NOT EDIT

package models

import "fmt"

const _JobStatus_name = "WaitingToRunRunningFinishedCannotRun"

var _JobStatus_index = [...]uint8{0, 12, 19, 27, 36}

func (i JobStatus) String() string {
	i -= 1
	if i < 0 || i >= JobStatus(len(_JobStatus_index)-1) {
		return fmt.Sprintf("JobStatus(%d)", i+1)
	}
	return _JobStatus_name[_JobStatus_index[i]:_JobStatus_index[i+1]]
}
